name: Refresh Hydrawise weather station

on:
  schedule:
    - cron: '30 3 * * *'
    - cron: '30 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Refresh weather station
        run: |
          python refresh.py
        env:
          HYDRAWISE_USERNAME: ${{ secrets.HYDRAWISE_USERNAME }}
          HYDRAWISE_PASSWORD: ${{ secrets.HYDRAWISE_PASSWORD }}
          HYDRAWISE_CLIENT_SECRET: ${{ secrets.HYDRAWISE_CLIENT_SECRET }}
          HYDRAWISE_CONTROLLERID: ${{ secrets.HYDRAWISE_CONTROLLERID }}
          HYDRAWISE_WEATHERSTATIONID: ${{ secrets.HYDRAWISE_WEATHERSTATIONID }}