name: Terraform Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write
  actions: write
  checks: write
  statuses: write
  security-events: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Set environment variables
        run: |
          echo "TF_VAR_hydrawise_username=${{ secrets.HYDRAWISE_USERNAME }}" >> $GITHUB_ENV
          echo "TF_VAR_hydrawise_password=${{ secrets.HYDRAWISE_PASSWORD }}" >> $GITHUB_ENV
          echo "TF_VAR_hydrawise_client_secret=${{ secrets.HYDRAWISE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "TF_VAR_hydrawise_controller_id=${{ secrets.HYDRAWISE_CONTROLLERID }}" >> $GITHUB_ENV
          echo "TF_VAR_hydrawise_weatherstation_id=${{ secrets.HYDRAWISE_WEATHERSTATIONID }}" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/hydrawise-github-apply-role
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init --upgrade

      - name: Terraform Apply
        run: terraform apply -auto-approve
